### ISSUE TITLE
Refresh table of contents on schema landing page

### ISSUE THREAD

**Issue by sujaypatil96** [GenomicsStandardsConsortium/mixs6.2_release_candidate#37]
The latest deployment of the MIXS documentation pages has links to the following sections on its index/landing page:

- [Checklists](https://microbiomedata.github.io/mixs-6-2-release-candidate/#checklists)
- [Packages](https://microbiomedata.github.io/mixs-6-2-release-candidate/#packages)
- [Combinations](https://microbiomedata.github.io/mixs-6-2-release-candidate/#combinations)
- [Enumerations](https://microbiomedata.github.io/mixs-6-2-release-candidate/#enumerations)
- [Types](https://microbiomedata.github.io/mixs-6-2-release-candidate/#types)
- [Subsets](https://microbiomedata.github.io/mixs-6-2-release-candidate/#subsets)

We should update/refresh the table of contents section to include only the following three links rather than including links to LinkML element pages like enums, subsets, etc.

- [Checklists](https://microbiomedata.github.io/mixs-6-2-release-candidate/#checklists)
- [Packages](https://microbiomedata.github.io/mixs-6-2-release-candidate/#packages)
- [Combinations](https://microbiomedata.github.io/mixs-6-2-release-candidate/#combinations)

What are your thoughts on this @turbomam @cmungall?

**Comment by turbomam** [comment]
We're trying not to overwhelm biologist type users, right?

OK, let's omit `types`. I do want to include `subsets` int eh table of contents. Could we also keep an enumeration page, like we did for all terms, on the left nav?

**Comment by turbomam** [comment]
see also
- #18

**Comment by turbomam** [comment]
see
- https://github.com/GenomicsStandardsConsortium/mixs/issues/635
