### ISSUE TITLE
Autogenerated web documentation should include a minimal table of all terms on it's own page

### ISSUE THREAD

**Issue by turbomam** [GenomicsStandardsConsortium/mixs6.2_release_candidate#4]

**Comment by jjkoehorst** [comment]
This would be highly appreciated and it does not have to be overly complex or extensive.
A simple table with ID, label and description might be sufficient. 

Most people use for example only the generic package but they might have additional metadata that has been used in other well defined packages. To have such a general overview in which they can apply basic `CTRL+F` methods could be very useful.

**Comment by turbomam** [comment]
@jjkoehorst can you elaborate on the "generic package"? That isn't anything that is defined in this schema.

**Comment by turbomam** [comment]
I agree that this will be useful and can easily be implemented, but only as a new, extremely large section on the [schema's landing page](https://genomicsstandardsconsortium.github.io/mixs6.2_release_candidate/)

The challenge will be building it on another page and providing a link on either the right (section-oriented) menu or the left (open-ended) menu

**Comment by jjkoehorst** [comment]
I am mostly familiar with the ENA submission procedures https://www.ebi.ac.uk/ena/browser/view/ERC000011 for which only date and location is obligatory and used in a lot of cases

**Comment by turbomam** [comment]
Move types section to separate page

also rename some of the sections

**Comment by turbomam** [comment]
sort elements in tables alphabetically

packages -> externsions

**Comment by turbomam** [comment]
@spatil96

**Comment by turbomam** [comment]
emphasize usability to a wide audience over comprehensiveness

**Comment by turbomam** [comment]
Where/how will all of the documentation from this repo be integrated with the GSC website?
