### ISSUE TITLE
Timeline for MIxS 6.2 release

### ISSUE THREAD

**Issue by ramonawalls** [GenomicsStandardsConsortium/mixs6.2_release_candidate#8]
We should aim to have all changes into the YAML file by the next CIG meeting on Sep. 26. At that point, no more conversions from the old spreadsheets to YAML should happen. 

At the CIG meeting, the TWG will present the MIxS 6.2 release with YAML as SOT. If approved by TWG, we can proceed with the release.

After the 6.2 release, we will implement conversion to schema sheets as SOT, as per issue #7 .

**Comment by turbomam** [comment]
whew!
